### ISSUE TITLE
Look import/export

### ISSUE THREAD

**Issue by bekkblando** [bekkblando/art_plugin#15]

**Comment by bekkblando** [comment]
I can load the data from the other directory into this one.

It will take me approx 7 hours.

**Comment by bekkblando** [comment]
I have received the data from the old site.  I'll start writing the code to load it in.

**Comment by macartscouncil** [comment]
OK, sounds good Bekk, keep me posted!
Thanks!

**Comment by bekkblando** [comment]
Artists names and additional information loaded.
