### ISSUE TITLE
Moving Directory

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#16]
Hey Bekk! Forgot to mention this last night. Can we move the "Arts Directory" to be under the "Arts Scene" Category? You'll see where I started a page there, you don't need to use that or anything but that's where it should be if possible! Thanks!

**Comment by bekkblando** [comment]
I'll move it!

**Comment by bekkblando** [comment]
Please Confirm

**Comment by macartscouncil** [comment]
Confirmed.
