### ISSUE TITLE
Main Categories 

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#17]
![screenshot 2016-07-18 10 18 23](https://cloud.githubusercontent.com/assets/18532651/16917783/0b9be32e-4cd1-11e6-8e44-e7371ae65641.png)

We still need to make the main categories a little smaller so "classes" doesn't site by itself.

**Comment by bekkblando** [comment]
Did my email address this well enough?

**Comment by macartscouncil** [comment]
Yes, it did. Would it be possible for the "Open Studios" category to be moved down also maybe (In this large scree mode? Or will that still mess things up in other views? I get what you're saying about it only being in my screen size's view but it would still be nice if we could find a way to amend it. Even if that means having Open Studios come down and then the responsive changes from there?

**Comment by bekkblando** [comment]
I have bumped down the font size to allow them to fit on the same row for a medium screen size.

Please Confirm

**Comment by macartscouncil** [comment]
That is great!
