### ISSUE TITLE
Category color when clicked

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#18]
When a category is selected can we have the box for example "Classes" remain the highlighted color while clicked so people can remember what they were on. 

Also for the sub categories. Ex: If someone clicked on "Classes" then "kids" classes would remain the highlighted dark color and "Kids" would remain the highlighted bold. 
![screenshot 2016-08-01 09 32 58](https://cloud.githubusercontent.com/assets/18532651/17295619/0e2f5abc-57cb-11e6-957e-4461fe494fab.png)
![screenshot 2016-08-01 09 25 14](https://cloud.githubusercontent.com/assets/18532651/17295620/0e2f71aa-57cb-11e6-890f-2f3ea815b9bb.png)

**Comment by bekkblando** [comment]
I've made some adjustments to fix the current but with "&" characters.  
Try it out and confirm functionality.

**Comment by macartscouncil** [comment]
Yep, seems to be working!

**Comment by bekkblando** [comment]
Issue has started again.  Perhaps a caching issue.

**Comment by bekkblando** [comment]
This one is giving me a bit of trouble.

I'm going to readdress it tomorrow or Sunday.

**Comment by bekkblando** [comment]
This should be resolved.

Please Confirm.

**Comment by macartscouncil** [comment]
Confirmed.
