### ISSUE TITLE
Thumbnail squishing

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#20]
The gallery homepage thumbnails are being squished into a square shape when the screen size changes. 
See image attached.
![squished](https://cloud.githubusercontent.com/assets/18532651/17556892/1b68bf60-5ee3-11e6-8d22-265cc120c17c.png)

**Comment by bekkblando** [comment]
This is due to setting the images as pixel units of height.  Is it acceptable for the images to be close to the specified pixel units but to scale when needed?  

If not another solution is possible but is more time consuming.

**Comment by macartscouncil** [comment]
I understand the frame moving and that's fine but I don't want the images within the frame to be squished and altered, if that makes sense. For example the horses in the image above were distorted and squished in.

**Comment by bekkblando** [comment]
I think this is related to the modal thumbnail image issue.  Let's schedule a time to discuss this as I'm not fully understanding how you guys want the post thumbnail editor to be able to interact with the page.

**Comment by macartscouncil** [comment]
OK, let me know when you can talk some time this week.

**Comment by bekkblando** [comment]
They will now adjust to the screen(thereby not squish). Make sure to crop the images as we discussed.
