### ISSUE TITLE
Remove italics from body font on modal

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#26]
![screenshot 2016-10-10 10 21 12](https://cloud.githubusercontent.com/assets/18532651/19239346/9eee159a-8ed3-11e6-9ec3-793c37030c9f.png)
 Font under "Artist Statement" and "Contact Information" should not be in italics.

**Comment by bekkblando** [comment]
Changed to normal OpenSans.  Please confirm.

**Comment by macartscouncil** [comment]
The info under "Contact Information" is still in italics.

**Comment by bekkblando** [comment]
No longer italics.
Please confirm.

**Comment by macartscouncil** [comment]
confirmed

**Comment by bekkblando** [comment]
Great
