### ISSUE TITLE
"Additional Info" Field

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#27]
Text written in the "Additional Info" Field are not showing up on the front end modal.

**Comment by bekkblando** [comment]
I'm having difficulty finding it on the original modal. Where should the content go?

**Comment by macartscouncil** [comment]
Under Artist Statement

**Comment by bekkblando** [comment]
This should be resolved.

**Comment by macartscouncil** [comment]
It's still not showing up on my end?

**Comment by bekkblando** [comment]
Hmmm, maybe clear your cache? We can do a google hangouts call with screen share.  It is appearing when I check it.

**Comment by macartscouncil** [comment]
How do I clear my cache?

**Comment by macartscouncil** [comment]
Now it is appearing. Do you remember when we talked about being able to write in anything for the header of "Additional Info" So that it would be bold like "Artist Statement?" But for example the header would say "Addional Info" or "Artist Statement" could say "Mission Statement" for organizations? 

I feel like at one point you had changed it to do that and it maybe reverted back?

**Comment by bekkblando** [comment]
Hmm I don't quite remember that, but I'll put it on the implementation list.

**Comment by bekkblando** [comment]
This feature is added.

Please Confirm.

**Comment by macartscouncil** [comment]
confirmed
