### ISSUE TITLE
Gallery Hompage Spacing

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#29]
![screenshot 2016-10-20 15 24 09](https://cloud.githubusercontent.com/assets/18532651/19574662/4e576268-96d9-11e6-8d59-890d5be659c6.png)

**Comment by bekkblando** [comment]
The problem isn't the aspect ratio it is that the images aren't all the same size(slightly different aspect ratio).  They need to be the same size to act correctly.

I can also set the size to be fixed, but since it's cropped it won't be stretched.

**Comment by macartscouncil** [comment]
Hmm... I've cropped them all to the 1.475 even went back to check.

**Comment by bekkblando** [comment]
They look correct on my screen.  Is the spacing still messed up?

**Comment by macartscouncil** [comment]
They haven't changed for me.
![screenshot 2016-11-08 09 02 54](https://cloud.githubusercontent.com/assets/18532651/20101956/3283a020-a592-11e6-9ac8-2a4831a5920e.png)

**Comment by macartscouncil** [comment]
Now it's only doing it under the "Open Studios" category in the same way as the image above.

**Comment by bekkblando** [comment]
Are you sure the crop was the same for all the images?

They seem to be rendering a few pixels smaller or larger than their neighbors.

**Comment by macartscouncil** [comment]
Yeah, I'm pretty sure. We can look at which ones are different and try changing them again... Last time I went back through and re-cropped all of them and nothing changed.
