### ISSUE TITLE
Gallery Image, Contact Info Not Showing

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#3]
The Gallery Image seems to be squished into the very top of the frame inside the modal. 

Address not showing up under "Contact Information"
"Contact Information" too high in the modal. 
![screenshot 2016-05-05 13 56 50](https://cloud.githubusercontent.com/assets/18532651/15052110/ec4aeef2-12c9-11e6-96aa-6d83f5abceb9.png)

**Comment by bekkblando** [comment]
This was a result of a theme conflict, I have resolved the squished image. However, problems are still present.

The image is not centered, and the navigation moves.

**Comment by bekkblando** [comment]
I have lowered the contact information and the address should appear even if a map is present.

Please confirm.

**Comment by macartscouncil** [comment]
Confirmed!
