### ISSUE TITLE
Categories Not Filtering

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#30]
Now that I've added more artists I am realizing that the categories are not actually filtering. When I choose Open Studios, 10 Central Avenue shows up, and when I choose different categories within it does not filter those either.

**Comment by macartscouncil** [comment]
After looking again. The Sub Categories do work. The header categories, however, show everything until you click on a sub category. 

This is how it should work: 
Ex:
If you click on "Museums and Galleries" only items checked as "Museums and Galleries" should show up. Then the sub categories should operate from there.

**Comment by bekkblando** [comment]
Is it every category or only Museums and Galleries(I've had problems with that one in particular in the past).

**Comment by macartscouncil** [comment]
It was all of them from what I could tell.

**Comment by bekkblando** [comment]
This should be resolved.  Please confirm.

**Comment by macartscouncil** [comment]
If you go to Open Studios and then try to go to the next page it shows 10 Central Avenue still which is not in Open Studios. It also "un-highlights" Open Studios as if you are no longer on the category?

**Comment by bekkblando** [comment]
I believe I've resolved this.  I'm going to do more testing in the morning.  It would be advantages to add some more artist to thoroughly test the pagination.

**Comment by macartscouncil** [comment]
I will add more artists today.

**Comment by macartscouncil** [comment]
The category "Jewelry and Glass" under both Visual Arts and Open Studios isn't showing artists who are checked as "Jewelry and Glass" 

Example artists: 
Purvi Ajmera
Kathy Young Albertelli

**Comment by macartscouncil** [comment]
I'm also adding "Sculpture and Metal" and "Drawing and Paper Arts" to that list.

**Comment by bekkblando** [comment]
I've added a fixed category for Sculpture and Metal and Jewelry and Glass.  

Currently, a misspelled duplicate of these two columns exists. I am removing it, but for immediate testing the correctly spelling can be selected.
