### ISSUE TITLE
Missing Categories

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#4]
Categories under "Visual Arts"  and "Open Studios" don't match the back end categories. Ex: "Clay" should be "Clay & Wood."

Category (mediums) not showing up under artist's name under thumbnail. Should be able to write in mediums for this part on the back end. 
For example: Under "Janina Tukarski Ellis" it should say "Painting"
![screenshot 2016-05-05 14 31 15](https://cloud.githubusercontent.com/assets/18532651/15052956/41321892-12ce-11e6-89b6-ffb2d6c7a092.png)

**Comment by bekkblando** [comment]
So you would like for a typed in medium to appear under the artist's name and not the category?

**Comment by macartscouncil** [comment]
Correct! I’ve been using Google Chrome.

**Comment by bekkblando** [comment]
I have added a category field and adjusted the names for the directory menu.  Please confirm.

**Comment by macartscouncil** [comment]
Confirmed.

**Comment by bekkblando** [comment]
Great!

**Comment by macartscouncil** [comment]
Sorry Bekk, I didn't look closely enough the first time. These are the categories that should be under "Visual Arts." "Open Studios"  is the same but there is no "organizations" category. 
![directory_visualarts](https://cloud.githubusercontent.com/assets/18532651/15542574/566e0f5e-225f-11e6-92de-14d0003b0a7a.jpg)

**Comment by macartscouncil** [comment]
Performing Arts should also have "organizations" and "other."

**Comment by bekkblando** [comment]
I have added "Organizations" and "Other" to Visual Arts, Open Studios and Performing Arts.

I also noted that Literary Arts has "Organizations"
Is this correct? ^

Please confirm correction.

**Comment by bekkblando** [comment]
Have you had a chance to look at this?

**Comment by macartscouncil** [comment]
Yes, Literary Arts should have "Organizations." 

Looks like Visual Arts and Open Studios are missing "Digital Arts and Printmaking." Also Open Studios should not have "Organizations."

**Comment by bekkblando** [comment]
This should be resolved.
Confirm?

**Comment by macartscouncil** [comment]
Under "Visual Arts" The categories should read:
organizations
clay & wood
digital arts
drawing & paper arts
fiber arts
jewelry & glass
mixed media
painting
printmaking
photography & video
sculpture & metal
other

Separate "digital arts and printmaking" and put into alphabetical order. 
All should be lower case. 

The same for Open Studios. 

Thanks!

**Comment by bekkblando** [comment]
Ok, I have made them lower cased, added the categories and put them in alphabetical order.

Please confirm.

**Comment by macartscouncil** [comment]
I don't see any of the artists or categories anymore?

**Comment by bekkblando** [comment]
Update broke it, it's fixed!

**Comment by bekkblando** [comment]
Is this resolved?

**Comment by macartscouncil** [comment]
Yes!
