### ISSUE TITLE
Slider Bar and Search Bar

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#5]
When you first reach the page the slider is cut off a bit. When you click on the slider the contents of the search bar (Aritsts Name and search icon) move up
![searchbar](https://cloud.githubusercontent.com/assets/18532651/15053158/32fb2704-12cf-11e6-888c-a345e121fb48.jpg)
![sliderbug](https://cloud.githubusercontent.com/assets/18532651/15053159/3301b948-12cf-11e6-85ce-d1b2c204aab2.jpg)

**Comment by bekkblando** [comment]
The cut off should be resolved(It was a theme, plugin conflict)

I am experiencing the other bug what browser are you using?

**Comment by bekkblando** [comment]
I'm using chrome and unable to get the ui bug is there anything else going on that might be of use?

Are you on a device or running an earlier version of chrome?

**Comment by macartscouncil** [comment]
Just looked again and it isn’t doing it anymore!

**Comment by bekkblando** [comment]
Great, I'll close the issue.
