### ISSUE TITLE
Printmaking Category Missing

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#6]
![screenshot 2016-05-05 15 20 06](https://cloud.githubusercontent.com/assets/18532651/15054361/006d2e3a-12d5-11e6-8a6b-a643f31c56e3.png)

**Comment by bekkblando** [comment]
Hey, can you add a bit of detail to this one?

**Comment by macartscouncil** [comment]
Sorry about that. The "Printmaking" category is missing.

**Comment by bekkblando** [comment]
I have added printmaking, please confirm.

**Comment by macartscouncil** [comment]
Confirmed

**Comment by bekkblando** [comment]
Great!
