### ISSUE TITLE
Sort Artists By Last Name

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#7]
If it is an individual artist listing it should sort automatically by last name. 
![screenshot 2016-05-05 15 27 31](https://cloud.githubusercontent.com/assets/18532651/15054534/febbe2d8-12d5-11e6-95eb-6c87f64d6694.png)

**Comment by bekkblando** [comment]
Is it ok for me to add different fields for the first name and last name?

There isn't a good way for me to differentiate between a first name and a last name in code but if I add a different field for each one then I can sort by last name effectively.  Other solutions exist that don't require this change but this is the fastest and easiest to implement.

**Comment by macartscouncil** [comment]
That is fine with me Bekk. Thanks!

**Comment by bekkblando** [comment]
This should be fixed.

Please confirm.

**Comment by macartscouncil** [comment]
Confirmed.

**Comment by bekkblando** [comment]
Great!
