### ISSUE TITLE
Contact Information Inside Modal

### ISSUE THREAD

**Issue by macartscouncil** [bekkblando/art_plugin#9]
Can we have the contact information at the top (above the phone number) and have it break into lines. 
Ex: 
Flatiron Building
1207 Pendleton Street
Greenville, SC 29611
(864) 905-3405
janina@janinaellis.com
www.janinaellis.com
![contact info](https://cloud.githubusercontent.com/assets/18532651/15185354/bdda04ee-1766-11e6-918b-41cabb7aee8e.png)

**Comment by bekkblando** [comment]
Is it ok for me to add different fields for the address?

There isn't a good way for me to differentiate between a street name and a neighbourhood in code but if I add a different field for each one then I can place them separately.

**Comment by macartscouncil** [comment]
That’s fine as well. Might need to have the following fields… 

Building/studio name

Street Address
City and Zip

**Comment by bekkblando** [comment]
I have added the fields and modified the order, please confirm.

**Comment by bekkblando** [comment]
Have you had a chance to review this?

**Comment by macartscouncil** [comment]
Confirmed!
